# for now, these dependencies cannot be fixed until solana-client updates them
[advisories]
ignore = [
    "RUSTSEC-2024-0344",
    "RUSTSEC-2022-0093",
    "RUSTSEC-2024-0375",
    "RUSTSEC-2025-0141",
    "RUSTSEC-2024-0388",
    "RUSTSEC-2025-0119",
    "RUSTSEC-2024-0436",
    "RUSTSEC-2021-0145",
]

[yanked]
enabled = true